### PR TITLE
ADD: pip support

### PR DESCRIPTION
**Pull request by kaczmarj**
Hello,

This pull request adds a `setup.py` script to make the project `pip`-installable, moves the main script `hpccm.py` into the `hpccm` namespace, and makes `hpccm` callable from the command-line.

Please note that the project version is not specified. It is blank in the call to `setup`, but that should be changed.

Users can install the project with pip:

From github:
- `$ pip install https://github.com/NVIDIA/hpc-container-maker/tarball/master`

From source directory
- `$ pip install .`

From source directory in development mode (changes in source are reflected without need for re-installation):
- `$ pip install -e .`

After any of those installations, `hpccm` is available on the command-line.

In the non-`pip` case, users can run
- `$ python -m hpccm.hpccm --help`

Thank you,
Jakub

### CODE REVIEW

**Comment by kaczmarj** [comment]
Seems like there are issues with some imports in python 2.7. Using absolute imports fixes that but changes the style. Would the maintainers be OK with this change? I can add that to this PR.

**Comment by samcmill** [comment]
What is your take on how to call it in the non-pip case?  

From the top level of a git checkout:
```
$ ./hpccm/hpccm.py --help
Traceback (most recent call last):
  File "./hpccm/hpccm.py", line 22, in <module>
    import argparse
  File "/usr/lib64/python3.4/argparse.py", line 87, in <module>
    import copy as _copy
  File "/home/smcmillan/git/external/kaczmarj/hpc-container-maker/hpccm/copy.py", line 25, in <module>
    import hpccm.config
  File "/home/smcmillan/git/external/kaczmarj/hpc-container-maker/hpccm/hpccm.py", line 27, in <module>
    class KeyValue(argparse.Action): # pylint: disable=too-few-public-methods
AttributeError: 'module' object has no attribute 'Action'
```

(This error is likely related to the python 2.7 relative imports issue flagged above.)

The README will also need to be updated to reflect the final calling behavior.

**Comment by samcmill** [comment]
Please add `license` and `url` metadata to `setup.py`:

```
license='Apache License Version 2.0',
url='https://github.com/NVIDIA/hpc-container-maker',
```

**Comment by samcmill** [comment]
For better or worse, the `hpccm.py` script as the way to invoke HPCCM is widespread.  I have no inherent objections to changing how it's called, but that needs to be a gradual, announced transition, not abrupt.

Can you please rename `hpccm/hpccm.py` to `hpccm/main.py` or `hpccm/cli.py` and add a top level `hpccm.py` that calls `main` from that file?  

The rest looks good.  This will be a great new capability.

**Comment by kaczmarj** [comment]
@samcmill - `hpccm/hpccm.py` is now `hpccm/cli.py`, and I added a top-level `hpcc.py` that calls the main function.

I would also recommend uploading this project to https://pypi.org/ after you tag it with a version. Then users can install this tools with

```
$ pip install hpccm
```

The python documentation on [packaging and distributing](https://packaging.python.org/guides/distributing-packages-using-setuptools/#packaging-your-project) is very handy for this.

**Comment by samcmill** [comment]
Looks good!  Thanks!

**Pull request merged**
