### PR TITLE
Updated year for MKL GPG

### PR DESCRIPTION
**Pull request by kristofkessler**
## Pull Request Description

Fixes https://github.com/NVIDIA/hpc-container-maker/issues/475

## Author Checklist
* [ ] Updated documentation (`pydocmd generate`) if any docstrings have been modified
* [x] Passes all unit tests

### CODE REVIEW

**Comment by samcmill** [comment]
Thanks for the fix.  

Can you please also update the affected tests in `test/test_mkl.py`?

**Comment by kristofkessler** [comment]
> Thanks for the fix.
> 
> Can you please also update the affected tests in `test/test_mkl.py`?

I updated `test/test_mkl.py`. Local pytest is successful.

One thing that could be considered: Should the MKL version be updated as well? If so, then this would probably be something for a separate pull request.

**Comment by samcmill** [comment]
> One thing that could be considered: Should the MKL version be updated as well? If so, then this would probably be something for a separate pull request.

MKL has been rebranded to oneMKL, so presumably quite a bit would need to change.  That raises the question of whether backwards compatibility with the "old" MKL should be retained or not?

**Comment by kristofkessler** [comment]
Would it be possible to create a new release of hpc container maker including this bugfix and make it available on pypi? Thanks.

**Comment by samcmill** [comment]
Yes.  If not tomorrow, then soon after Thanksgiving.

**Pull request merged**
